#!/usr/bin/env bash

set -e

# source the common build functions
SCRIPT_DIR=$(dirname "$0")
source "$SCRIPT_DIR/ios_build_functions.sh"

setup_build_environment

if [ -d "$INSTALL_PATH/openssl.xcframework" ]
then
    echo "Nothing to be done."
    exit 0
fi

pushd "$ROOT_PATH/External/openssl-apple"

./build-libssl.sh --version=1.1.1l --targets="ios-sim-cross-x86_64 ios-sim-cross-arm64 ios64-cross-arm64"
./create-openssl-framework.sh static

cp -r frameworks/openssl.xcframework "$INSTALL_PATH"

for OPENSSL_PLATFORM_NAME in iPhoneOS iPhoneSimulator
do
    PLATFORM=$(echo "$OPENSSL_PLATFORM_NAME" | tr '[:upper:]' '[:lower:]')
    PLATFORM_INSTALL_PATH="$INSTALL_PATH/$PLATFORM"
    cp -r include/openssl "$PLATFORM_INSTALL_PATH/include"
    lipo -create bin/$OPENSSL_PLATFORM_NAME*.sdk/lib/libcrypto.a -output "$PLATFORM_INSTALL_PATH/lib/libcrypto.a"
    lipo -create bin/$OPENSSL_PLATFORM_NAME*.sdk/lib/libssl.a -output "$PLATFORM_INSTALL_PATH/lib/libssl.a"

    PCK_CONFIG_DIR=$(find bin/$OPENSSL_PLATFORM_NAME*.sdk/lib/pkgconfig -type d | head -n 1)
    cp "$PCK_CONFIG_DIR/"*.pc "$PLATFORM_INSTALL_PATH/lib/pkgconfig"
    sed -e "s|^prefix=.*$|prefix=$PLATFORM_INSTALL_PATH|" \
        -i '' "$PLATFORM_INSTALL_PATH/lib/pkgconfig/"{libcrypto,libssl,openssl}.pc
done

popd
